# Generated by Django 3.0.5 on 2020-06-18 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import myapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AromaUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(choices=[(1, 'Ingredient Cosmetique'), (2, 'Huile Beurre Vegetal'), (3, 'Huile Vegetale'), (4, 'Beurre Veteal'), (5, 'Macreat Huileux'), (6, 'Hydrolat'), (7, 'Huile Essentielle'), (8, 'Actif Cosmetique'), (9, 'Poudre Plante'), (10, 'Extrait Plante'), (11, 'Fragrance Naturelle'), (12, 'Exfoliant Naturel'), (13, 'Argile'), (14, 'Colorant'), (15, 'Emolient'), (16, 'Agent De Texture'), (17, 'Cire'), (18, 'Gomme'), (19, 'Alcool Gras'), (20, 'Tensioactif'), (21, 'Emulsifiant'), (22, 'Conservateur'), (23, 'Antioxydant'), (24, 'Ajustateur Ph'), (25, 'Base Neutre'), (26, 'Container'), (27, 'Pot'), (28, 'Flacon'), (29, 'Materiel Fabrication'), (30, 'Materiel Dosage Transfert'), (31, 'Materiel Melange'), (32, 'Materiel Maquillage')])),
                ('label', models.CharField(max_length=25)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='myapp.Category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Packaging',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unit', myapp.models.MeasurementUnitFields(choices=[(0, 'None'), (1, 'Ml'), (2, 'Grams'), (3, 'Goutte'), (4, 'Masque')], default=0)),
                ('price', models.FloatField()),
            ],
            bases=(models.Model, myapp.models.MeasurementUnitModelBased),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('containers_flag', models.IntegerField(default=0)),
                ('product_details_flag', models.IntegerField(default=0)),
                ('properties_flag', models.IntegerField(default=0)),
                ('url', models.URLField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('container_type', models.IntegerField(choices=[(0, 'None'), (1, 'Pot'), (2, 'Flacon Simple'), (3, 'Flacon Dentifrice'), (4, 'Flacon Roll On'), (5, 'Flacon Mousseur'), (6, 'Flacon Compte Goutte'), (7, 'Flacon Spray'), (8, 'Flacon Creme'), (9, 'Flacon Savon'), (10, 'Flacon Applicateur'), (11, 'Etui Stick'), (12, 'Etui Levre'), (13, 'Flacon Twister'), (14, 'Bouchon'), (15, 'Base'), (16, 'Airless')])),
                ('conservation', models.PositiveSmallIntegerField()),
                ('final_quantity', models.PositiveIntegerField()),
                ('final_unit', myapp.models.MeasurementUnitFields(choices=[(0, 'None'), (1, 'Ml'), (2, 'Grams'), (3, 'Goutte'), (4, 'Masque')], default=0)),
                ('level', models.IntegerField(choices=[(1, 'Starter'), (2, 'Advanced'), (3, 'Confirmed')], default=1)),
                ('properties_flag', models.IntegerField(default=0)),
                ('time', models.PositiveSmallIntegerField()),
                ('url', models.URLField()),
            ],
            bases=(models.Model, myapp.models.MeasurementUnitModelBased),
        ),
        migrations.CreateModel(
            name='UserStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=0)),
                ('unit', myapp.models.MeasurementUnitFields(choices=[(0, 'None'), (1, 'Ml'), (2, 'Grams'), (3, 'Goutte'), (4, 'Masque')], default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.AromaUser')),
            ],
            bases=(models.Model, myapp.models.MeasurementUnitModelBased),
        ),
        migrations.CreateModel(
            name='RecipeQuantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_quantity', models.FloatField(default=0)),
                ('unit', myapp.models.MeasurementUnitFields(choices=[(0, 'None'), (1, 'Ml'), (2, 'Grams'), (3, 'Goutte'), (4, 'Masque')], default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='myapp.Product')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='myapp.Recipe')),
            ],
            bases=(models.Model, myapp.models.MeasurementUnitModelBased),
        ),
        migrations.CreateModel(
            name='RecipeBasket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basket_recipes', to='myapp.AromaUser')),
            ],
        ),
        migrations.CreateModel(
            name='ProductBasket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packaging', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Packaging')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.AromaUser')),
            ],
        ),
        migrations.AddField(
            model_name='packaging',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packagings', to='myapp.Product'),
        ),
    ]
